/work/mupyramid/gencoinz /data2/Pyramid/data/1/out1_coin_all.dat.gz -o c1.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/2/out2_coin_all.dat.gz -o c2.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/3/out3_coin_all.dat.gz -o c3.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/4/out4_coin_all.dat.gz -o c4.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/5/out5_coin_all.dat.gz -o c5.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/6/out6_coin_all.dat.gz -o c6.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/7/out7_coin_all.dat.gz -o c7.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/8/out8_coin_all.dat.gz -o c8.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/9/out9_coin_all.dat.gz -o c9.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/10/out10_coin_all.dat.gz -o c10.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/11/out11_coin_all.dat.gz -o c11.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/12/out12_coin_all.dat.gz -o c12.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/13/out13_coin_all.dat.gz -o c13.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/14/out14_coin_all.dat.gz -o c14.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/15/out15_coin_all.dat.gz -o c15.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/16/out16_coin_all.dat.gz -o c16.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/17/out17_coin_all.dat.gz -o c17.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/18/out18_coin_all.dat.gz -o c18.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/19/out19_coin_all.dat.gz -o c19.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/20/out20_coin_all.dat.gz -o c20.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/21/out21_coin_all.dat.gz -o c21.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/22/out22_coin_all.dat.gz -o c22.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/23/out23_coin_all.dat.gz -o c23.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/24/out24_coin_all.dat.gz -o c24.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/25/out25_coin_all.dat.gz -o c25.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/26/out26_coin_all.dat.gz -o c26.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/27/out27_coin_all.dat.gz -o c27.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/28/out28_coin_all.dat.gz -o c28.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/29/out29_coin_all.dat.gz -o c29.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/30/out30_coin_all.dat.gz -o c30.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/31/out31_coin_all.dat.gz -o c31.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/32/out32_coin_all.dat.gz -o c32.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/33/out33_coin_all.dat.gz -o c33.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/34/out34_coin_all.dat.gz -o c34.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/35/out35_coin_all.dat.gz -o c35.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/36/out36_coin_all.dat.gz -o c36.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/37/out37_coin_all.dat.gz -o c37.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/38/out38_coin_all.dat.gz -o c38.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/39/out39_coin_all.dat.gz -o c39.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/40/out40_coin_all.dat.gz -o c40.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/41/out41_coin_all.dat.gz -o c41.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/42/out42_coin_all.dat.gz -o c42.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/43/out43_coin_all.dat.gz -o c43.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/44/out44_coin_all.dat.gz -o c44.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/45/out45_coin_all.dat.gz -o c45.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/46/out46_coin_all.dat.gz -o c46.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/47/out47_coin_all.dat.gz -o c47.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/48/out48_coin_all.dat.gz -o c48.dat.gz
/work/mupyramid/gencoinz /data2/Pyramid/data/49/out49_coin_all.dat.gz -o c49.dat.gz
